<?php

/**
 * @file
 * Contains cookies_video.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;
use Drupal\cookies\CookiesKnockOutService;

/**
 * Implements hook_help().
 */
function cookies_video_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
      // Main module help for the cookies_ga module.
    case 'help.page.cookies_video':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Submodule of COOKiES to manage video media items (by "media" module) inside of COOKiES consent management.') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_preprocess_HOOK().
 */
function cookies_video_preprocess_field(&$variables) {
  $formatter = $variables["element"]["#formatter"];
  if (!in_array($formatter, ['oembed', 'blazy_oembed'])) {
    // Return early if not a handled formatter:
    return;
  }
  $doKo = CookiesKnockOutService::getInstance()->doKnockOut();
  if ($doKo) {
    foreach ($variables["items"] as &$item) {
      switch ($formatter) {
        case 'oembed':
          _cookies_video_preprocess_field_item_oembed($item);
          break;
        case 'blazy_oembed':
          _cookies_video_preprocess_field_item_blazy_oembed($item);
          break;
      }

      // Attach library.
      if (!isset($item["content"]["#attached"])) {
        $item["content"]["#attached"] = ["library" => []];
      }
      if (!isset($item["content"]["#attached"]["library"])) {
        $item["content"]["#attached"]["library"] = [];
      }
      $item["content"]["#attached"]["library"][] = 'cookies_video/default';
    }
  }
}

function _cookies_video_preprocess_field_item_oembed(&$item) {
  // Move src to data-src and replace src by fallback.
  $src = $item["content"]["#attributes"]["src"];
  $item["content"]["#attributes"]["data-src"] = $src;
  $item["content"]["#attributes"]["src"] = '';

  // Set marker class.
  if (!isset($item["content"]["#attributes"]["class"]) || !is_array($item["content"]["#attributes"]["class"])) {
    $item["content"]["#attributes"]["class"] = [];
  }
  $item["content"]["#attributes"]["class"][] = 'cookies-video';
}

function _cookies_video_preprocess_field_item_blazy_oembed(&$item) {
  // Hide the blazy preview by default and set marker class.
  // This has to be done in ['#build'] for blazy to take effect:
  $item["content"]["#build"]['attributes']["class"][] = 'hidden';
  $item["content"]["#build"]['attributes']["class"][] = 'cookies-video-blazy-oembed';
}
