<?php

use Drupal\Core\Form\FormStateInterface;

function verathon_customization_h5p_styles_alter(&$styles, $libraries, $mode) {
  $styles[] = (object) array(
    // Path relative to drupal root
    'path' => drupal_get_path('module', 'verathon_customization') . '/css/custom-h5p-overrides.css',
    // Cache buster
    'version' => '?ver=1',
  );
}
function verathon_customization_h5p_scripts_alter(&$scripts, $libraries, $mode) {
    $scripts[] = (object) array(
      // Path relative to drupal root
      'path' => drupal_get_path('module', 'verathon_customization') . '/js/custom-h5p-overrides.js',
      // Cache buster
      'version' => '?ver=1',
    );
}

/**
* Implements hook_form_alter().
*/
function verathon_customization_form_alter(&$form, FormStateInterface $form_state, $form_id) {
  if ($form_id === 'views_exposed_form' && isset($form['field_product_line'])) {
    if ('views-exposed-form-et-search-block-search' === $form['#id']) {
      // Rename the All option label.
      $form['field_product_line']['#options']['All'] = t('All Products');
    }
    if ('views-exposed-form-acquia-search-search' === $form['#id']) {
      // Rename the All option label.
      $form['field_product_line']['#options']['All'] = t('All');
    }
  }
}
