<?php

use Drupal\Core\Form\FormStateInterface;
use Drupal\Core\Render\Markup;
use Drupal\node\Entity\Node;

function verathon_customization_h5p_styles_alter(&$styles, $libraries, $mode) {
  $styles[] = (object) array(
    // Path relative to drupal root
    'path' => drupal_get_path('module', 'verathon_customization') . '/css/custom-h5p-overrides.css',
    // Cache buster
    'version' => '?ver=1',
  );
}
function verathon_customization_h5p_scripts_alter(&$scripts, $libraries, $mode) {
    $scripts[] = (object) array(
      // Path relative to drupal root
      'path' => drupal_get_path('module', 'verathon_customization') . '/js/custom-h5p-overrides.js',
      // Cache buster
      'version' => '?ver=1',
    );
}

/**
* Implements hook_form_alter().
*/
function verathon_customization_form_alter(&$form, FormStateInterface $form_state, $form_id) {
  if ($form_id === 'views_exposed_form' && isset($form['field_product_line'])) {
    if ('views-exposed-form-et-search-block-search' === $form['#id']) {
      // Rename the All option label.
      $form['field_product_line']['#options']['All'] = t('All Products');
    }
    if ('views-exposed-form-acquia-search-search' === $form['#id']) {
      // Rename the All option label.
      $form['field_product_line']['#options']['All'] = t('All');
      $form['#attached']['library'][] = 'verathon_customization/verathon_search';
    }
  }
}

/**
 * Implements hook_preprocess_html().
 */
function cohesion_theme_preprocess_html(array &$variables) {
  $current_theme = \Drupal::service('theme.manager')->getActiveTheme()->getName();

  if ($current_theme !== 'cohesion_theme') {
    return;
  }

  $path = \Drupal::service('path.current')->getPath();
  $alias = \Drupal::service('path_alias.manager')->getAliasByPath($path);
  $path_args = explode('/', $path);
  $path_args = array_filter($path_args);

  if ($path_args[1] == 'node' && is_numeric($path_args[2])) {
    $node = Node::load($path_args[2]);
    $type = ucwords($node->getType());
  }

  $script = Markup::create("dataLayer = [{
    'pageCategory': '$type',
    'sitesection' : '$alias',
  }];");

  $variables['page']['#attached']['html_head'][] = [['#tag' => 'script', '#value' => $script], 'dataLayer'];
}
