# Schema for the configuration files of the Acquia Content Hub moderation module.
acquia_contenthub_moderation.settings:
  type: config_object
  label: 'Acquia Content Hub moderation settings'
  mapping:
    workflows:
      type: sequence
      label: 'Workflows using Default Import State for Content Hub'
      sequence:
        type: mapping
        label: 'Workflow import state'
        mapping:
          moderation_state:
            type: string
            label: 'Default Import Moderation State'
