<?php

/**
 * @file
 * Contains cookies.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function cookies_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    case 'help.page.cookies':
      $text = file_get_contents(__DIR__ . '/README.md');
      if (!\Drupal::moduleHandler()->moduleExists('markdown')) {
        return '<pre>' . Html::escape($text) . '</pre>';
      }
      else {
        // Use the Markdown filter to render the README.
        $filter_manager = \Drupal::service('plugin.manager.filter');
        $settings = \Drupal::configFactory()->get('markdown.settings')->getRawData();
        $config = ['settings' => $settings];
        $filter = $filter_manager->createInstance('markdown', $config);
        return $filter->process($text, 'en');
      }
  }
  return NULL;
}

/**
 * Implements hook_theme().
 */
function cookies_theme() {
  return [
    'cookies_container' => [
      'variables' => [
        'id' => NULL,
        'styles' => NULL,
      ],
    ],
    'cookies_docs_group' => [
      'variables' => [
        'attributes' => [],
        'label' => NULL,
        'items' => [],
      ],
    ],
    'cookies_docs_service' => [
      'variables' => [
        'attributes' => [],
        'label' => NULL,
        'external_link_url' => [],
        'external_link_text' => [],
        'content' => [],
        'edit_link_url' => [],
        'edit_link_text' => [],
      ],
    ],
  ];
}


/**
 * Implements hook_menu_links_discovered_alter().
 */
 function cookies_menu_links_discovered_alter(&$links) {

  /*
   * Define the "Cookie settings" menu item in Tools.
   * Dynamic equivalent of links.menu.yml entry, but we need to set the URL
   * dynamically because the dialog open fragment can be configured in COOKiES
   * settings.
   *
   * cookies.open_cookie_consent_dialog:
   * title: "Cookie settings"
   * description: "Open the cookie consent dialog."
   * url: "internal:<DYNAMIC:#editCookieSettings>"
   * menu_name: tools
   * options:
   *   attributes:
   *     class:
   *       - cookies-open-cookie-consent-dialog
   */
  $open_settings_hash = \Drupal::config('cookies.config')->get('open_settings_hash');
  if (!empty($open_settings_hash)) {
    $links['cookies.open_cookie_consent_dialog'] = [
      'title' => "Cookie settings",
      'description' => "Open the cookie consent dialog.",
      'url' => "internal:#" .  htmlspecialchars($open_settings_hash, ENT_QUOTES | ENT_SUBSTITUTE, 'UTF-8'),
      'menu_name' => 'tools',
      'provider' => 'cookies',
      'options' => [
        'attributes' => [
          'class' => 'cookies-open-cookie-consent-dialog'
        ]
      ]
    ];
  }
}
