<?php

/**
 * @file
 * Primary module hooks for Verathon Bflex Calculator module.
 *
 * @DCG
 * This file is no longer required in Drupal 8.
 * @see https://www.drupal.org/node/2217931
 */

/**
 * @inheritDoc
 *
 * Implements hook_theme_suggestions_HOOK_alter().
 */
function verathon_bflex_calculator_theme_suggestions_form_alter(&$suggestions, $variables)
{
  if ($variables['theme_hook_original'] == 'form') {
    $suggestions[] = 'form__' . $variables['element']['#form_id'];
  }
}

function verathon_bflex_calculator_preprocess_form(&$variables)
{
  if ($variables['element']['#form_id'] == 'verathon_bflex_calculator_verathon_bflex_calculator') {
    $variables['config'] = \Drupal::config('verathon_bflex_calculator.settings')->get();
  }
}

/**
 * @inheritDoc
 *
 * Implements hook_theme_registry_alter().
 */
function verathon_bflex_calculator_theme($existing, $type, $theme, $path)
{
  return [
    'form__verathon_bflex_calculator_verathon_bflex_calculator' => [
      'render element' => 'form',
      'variables' => [
        'config' => \Drupal::service('config.factory')->getEditable('verathon_bflex_calculator.settings')->get()
      ],
    ],
    'result__verathon_bflex_calculator_verathon_bflex_calculator' => [
      'variables' => [
        'config' => \Drupal::service('config.factory')->getEditable('verathon_bflex_calculator.settings')->get(),
        'form_values' => NULL,
      ],
    ],
  ];
}
